### ISSUE TITLE
How to update docker compose file for dockerswarm deployment with traefik

### ISSUE THREAD

**Issue by jasmindevgirl** [Buuntu/fastapi-react#125]
Hi thanks for this great project generator. It works great but I'm trying to figure out how to deploy it.
I read the tutorial on dockerswarm rocks but I don't know how to update the docker compose file as suggested in the docs.

I tried it like this
```
version: '3.7'
services:
  traefik:
    # Use the latest Traefik image
    image: traefik:v2.2
    ports:
        # Listen on port 80, default for HTTP, necessary to redirect to HTTPS
        - target: 80
        published: 80
        mode: host
        # Listen on port 443, default for HTTPS
        - target: 443
        published: 443
        mode: host
    deploy:
        placement:
        constraints:
            # Make the traefik service run only on the node with this label
            # as the node with it has the volume for the certificates
            - node.labels.traefik-public.traefik-public-certificates == true
        labels:
        # Enable Traefik for this service, to make it available in the public network
        - traefik.enable=true
        # Use the traefik-public network (declared below)
        - traefik.docker.network=traefik-public
        # Use the custom label "traefik.constraint-label=traefik-public"
        # This public Traefik will only use services with this label
        # That way you can add other internal Traefik instances per stack if needed
        - traefik.constraint-label=traefik-public
        # admin-auth middleware with HTTP Basic auth
        # Using the environment variables USERNAME and HASHED_PASSWORD
        - traefik.http.middlewares.admin-auth.basicauth.users=${USERNAME?Variable not set}:${HASHED_PASSWORD?Variable not set}
        # https-redirect middleware to redirect HTTP to HTTPS
        # It can be re-used by other stacks in other Docker Compose files
        - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
        - traefik.http.middlewares.https-redirect.redirectscheme.permanent=true
        # traefik-http set up only to use the middleware to redirect to https
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-http.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-http.entrypoints=http
        - traefik.http.routers.traefik-public-http.middlewares=https-redirect
        # traefik-https the actual router using HTTPS
        # Uses the environment variable DOMAIN
        - traefik.http.routers.traefik-public-https.rule=Host(`${DOMAIN?Variable not set}`)
        - traefik.http.routers.traefik-public-https.entrypoints=https
        - traefik.http.routers.traefik-public-https.tls=true
        # Use the special Traefik service api@internal with the web UI/Dashboard
        - traefik.http.routers.traefik-public-https.service=api@internal
        # Use the "le" (Let's Encrypt) resolver created below
        - traefik.http.routers.traefik-public-https.tls.certresolver=le
        # Enable HTTP Basic auth, using the middleware created above
        - traefik.http.routers.traefik-public-https.middlewares=admin-auth
        # Define the port inside of the Docker service to use
        - traefik.http.services.traefik-public.loadbalancer.server.port=8080
    volumes:
        # Add Docker as a mounted volume, so that Traefik can read the labels of other services
        - /var/run/docker.sock:/var/run/docker.sock:ro
        # Mount the volume to store the certificates
        - traefik-public-certificates:/certificates
    command:
        # Enable Docker in Traefik, so that it reads labels from Docker services
        - --providers.docker
        # Add a constraint to only use services with the label "traefik.constraint-label=traefik-public"
        - --providers.docker.constraints=Label(`traefik.constraint-label`, `traefik-public`)
        # Do not expose all Docker services, only the ones explicitly exposed
        - --providers.docker.exposedbydefault=false
        # Enable Docker Swarm mode
        - --providers.docker.swarmmode
        # Create an entrypoint "http" listening on address 80
        - --entrypoints.http.address=:80
        # Create an entrypoint "https" listening on address 80
        - --entrypoints.https.address=:443
        # Create the certificate resolver "le" for Let's Encrypt, uses the environment variable EMAIL
        - --certificatesresolvers.le.acme.email=${EMAIL?Variable not set}
        # Store the Let's Encrypt certificates in the mounted volume
        - --certificatesresolvers.le.acme.storage=/certificates/acme.json
        # Use the TLS Challenge for Let's Encrypt
        - --certificatesresolvers.le.acme.tlschallenge=true
        # Enable the access log, with HTTP requests
        - --accesslog
        # Enable the Traefik log, for configurations and errors
        - --log
        # Enable the Dashboard and API
        - --api
    networks:
        # Use the public network created to be shared between Traefik and
        # any other service that needs to be publicly available with HTTPS
        - traefik-public
#   nginx:
#     image: nginx:1.17
#     volumes:
#       - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
#     ports:
#       - 8000:80
#     depends_on:
#       - backend

  redis:
    image: redis
    ports:
      - 6379:6379

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  worker:
    build:
      context: backend
      dockerfile: Dockerfile
    command: celery worker -A app.tasks --loglevel=DEBUG -Q main-queue -c 1

  flower:  
    image: mher/flower
    command: flower --broker=redis://redis:6379/0 --port=5555
    ports:  
        - 5555:5555
    depends_on:
      - "redis"

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    command: python app/main.py
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:password@postgres:5432/postgres'
    depends_on:
      - "postgres"


volumes:
  db-data:
```

But it's not working... What am I doing wrong? Or is there a template file for deployment?
Thanks
